# Generated by Django 3.1.7 on 2021-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=127, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=127, null=True)),
                ('city', models.CharField(blank=True, max_length=127, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('postcode', models.CharField(blank=True, max_length=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('business_status', models.CharField(blank=True, max_length=32, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('geometry', models.TextField(blank=True)),
                ('listed_name', models.CharField(blank=True, max_length=127, null=True)),
                ('place_id', models.CharField(blank=True, max_length=127, null=True)),
                ('formatted_address', models.TextField(blank=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
