# Generated by Django 3.1.7 on 2021-03-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210308_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='geometry',
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
