# Generated by Django 3.1.7 on 2021-03-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20210308_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('name', models.CharField(max_length=63, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=63, null=True)),
                ('last_name', models.CharField(blank=True, max_length=63, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('email_type', models.CharField(blank=True, max_length=63, null=True)),
                ('email_confidence', models.IntegerField(blank=True, null=True)),
                ('email_sources', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=63, null=True)),
                ('seniority', models.CharField(blank=True, max_length=63, null=True)),
                ('department', models.CharField(blank=True, max_length=63, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=63, null=True)),
                ('twitter', models.CharField(blank=True, max_length=63, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=63, null=True)),
                ('verification_date', models.CharField(blank=True, max_length=63, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
    ]
