# Generated by Django 3.1.7 on 2021-03-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_domain_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.domain'),
        ),
    ]
